version: '3'
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        env_file:
            - .env
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/app.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
