name: DeployTest

on:
  push:
    branches:
      - main

env:
  DEPLOY_DEV_ENV: ${{ env.DEPLOY_DEV_ENV }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to deployment directory
      run: |
        pwd
        cp -R ./* /var/www/laravel_demo

    - name: Change to deployment directory
      run: cd /var/www/laravel_demo

    - name: Create .env file
      run: echo "$DEPLOY_DEV_ENV" > .env

    - name: Run composer install
      run: docker-compose exec -T app composer install

    - name: Run database migrations
      run: docker-compose exec -T app php artisan migrate

    - name: Cache routes
      run: docker-compose exec -T app php artisan route:cache

    - name: Cache configuration
      run: docker-compose exec -T app php artisan config:cache

    - name: Dump autoload
      run: docker-compose exec -T app composer dumpautoload
